name: Build multi-platform executables

on:
  push:
    branches:    
      - master

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install MKL (BLAS & LAPACK) with Anaconda
      run: conda install -c anaconda mkl

    - name: Configure with CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_C_COMPILER=gcc

    - name: Build with Make
      run: cmake --build ${{github.workspace}}/build

  mac-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install MKL (BLAS & LAPACK) with Anaconda
      run: |
        sudo chown -R runner:staff $CONDA
        conda install -c anaconda mkl

    - name: Configure with CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_Fortran_COMPILER=gfortran-11 -DCMAKE_C_COMPILER=gcc-11

    - name: Build with Make
      run: cmake --build ${{github.workspace}}/build

  windows-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: >-
          git
          make
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-openblas
          mingw-w64-x86_64-lapack

    - uses: actions/checkout@v2

    - name: Configure with CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "MSYS Makefiles" -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_C_COMPILER=gcc

    - name: Build with Make
      run: cmake --build ${{github.workspace}}/build
