name: Build multi-platform executables

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    # to enable command-line usage of conda (not sure why)
    - uses: s-weigand/setup-conda@v1

    - name: Install MKL (BLAS & LAPACK) with Anaconda
      run: conda install -c anaconda mkl

    - name: Configure with CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build with Make
      run: cmake --build ${{github.workspace}}/build
