name: Build multi-platform executables

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            fc: gfortran
            cc: gcc

          - os: macos-latest
            fc: gfortran-10
            cc: gcc-10


    steps:
    - uses: actions/checkout@v2

    - name: Fix Anaconda path permissions (MacOS only)
      run: sudo chown -R runner:staff $CONDA
      if: ${{ matrix.os == 'macos-latest' }}

    - name: Install MKL (BLAS & LAPACK) with Anaconda
      run: conda install -c anaconda mkl

    - name: Configure with CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_Fortran_COMPILER=${{matrix.fc}} -DCMAKE_C_COMPILER=${{matrix.cc}}

    - name: Build with Make
      run: cmake --build ${{github.workspace}}/build
